name: Update MV Calendar

on:
  schedule:
    - cron: '0 */6 * * *'  # Toutes les 6h
  workflow_dispatch:  # permet de le lancer manuellement

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Download and filter ICS
      run: |
        python fetch_and_filter.py

    - name: Push to gh-pages
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv ADE_UCA_MV_filtré.ics index.ics
        git add index.ics
        git commit -m "Update MV calendar"
        git push -f origin gh-pages
